replicaCount: 1

image:
  repository: ghcr.io/dream2405/healthy_meal_backend 
  pullPolicy: Always
  tag: "latest" # 기본 태그

service:
  type: ClusterIP
  port: 80

externalDatabase:
  host: "dummy-host.example.com"

volume:
  size: 8Gi
  storageClassName: longhorn-dev
  replicaCount: "1"
  claimName: longhorn-volv-pvc
  mountPath: /data
  accessModes:
    - ReadWriteOnce