replicaCount: 1

image:
  repository: ghcr.io/dream2405/healthy_meal_backend 
  pullPolicy: Always
  tag: "latest" # 기본 태그

service:
  type: ClusterIP
  port: 80

externalDatabase:
  host: "dummy-host.example.com"