---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mysql-init-scripts
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    init.sql: AgA9FGVbmCkNYcq0H/BUAao3vTRDpYAf7k5xlMWjC+vnJ2vQkrnGWJ+TB/+nZsNhoxgC+Z3ehVS3r16gaMiTd9VpP2Ea0CTkv/Aw5GSrJgNd/VH2nLjYO7xTsDoBwNghHHQaG/kFrEMYSJlDVNxI2DEHX/O0tfjPZ8KUhIyGV1ZRfkPAG9aNHG7q1OU4zv8erE+2qvU5KahXCsMTEO4b7mb5Sa8FrGF8J+9xuVZV6JAJD6sY5IkYGig4bejivV3j47BttG7/OGqq7E+xDR8dVQCO49FI/RXpHTzaV2CTwjyNcAvfcTMp0FkLjxKKU3WB79j+JTt9IG6rRTHsPijV5iQDwoFR/eYDAvBwI2+9sbTsBgRNPRBsc3HuG78GWAwjRiE+ya/3oOheB3efaUANxLlSJeVbNd+rbU6hzDgv1Q99cHlMybnEMO53EFEaeJC0yzFlWJ80nQ4H1extDNkImctPXJE40r1Rfh2wyFaewI+0UJKT/7OMKZjpgEADceMMy1LALyUoBW4mPxgKng8C44z3t/DfLrH2qo1T3IHLOVt8JknQxhFtLNrKBg/tDEZ+vnONw5SqFtr+EprXmq2I48V/Nu2Ms2lgRuBCNSHbx/0/fTPWOZwuRyoZryOnqSBAXnZRiqoPbYJ2cxRMBAw/F3vzNd/i57ZEdxASFskCTX1tzMa7lD5aK62n0kACmbouMzaKOslSthvnz5iMB3hEWjA0dnv4MlNCiu2ykmI5NwkZHTtSjPDdqT+pPPZUlFp3gL+xn8o5PEgJdb5IARVFDScqkh4g+5OclitL0LtQbdO1bYK/3sX/TOBhkXDNsse4jrRIZNLBcSCk5IcdQLdd3+jlSG2tNymPtIa7YFB1Ea4wGtsTwJ2WH1ERFXqwYSC3GsjtshWtEwgxnUJWfoxoETOvujueZ+npdqx0pYQB5xD9sy+oa2IVxJnqZuKC
  template:
    metadata:
      name: mysql-init-scripts
      namespace: {{ .Release.Namespace }}
