---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mysql-init-scripts
  namespace: mysql-dev
spec:
  encryptedData:
    init.sql: AgA44uC8KLOUKtX0++sDOczo2iIBxTP6cZh0WH10m6BW6/cU3NPTI9rbH2x2Ym1V/uy6ByUw2t4CzFmlt6VOl51u7s6PtGFeIC9KS/0CEgmd8swccpm8kQ7stgM0B1bs8muBgQ2NViZrfvbBlF926T/g6+w6Nja+eqyi9P89deDjYuzGnrV06nPRyQx/VqyCNSFJv3XWiOPof4mlXCCm3WdI51gPat9K0fPwIFkYn+MMWlGQM9mxnvExImpy7nJFQB5MHS4PcEDSIx1pQEAdQd2kVMFcS+S27WuNVd6mAw6LJrS6wyVLXxtB4zQkGqQxfaw1IcV/npgVltRIUZVIlI886NBHOkKipg6vZdZ/lYZcz/XWOdbL/vdc1VeKvtV7VTSGrQBpa9e0j8qbnwIjmlOxCoRyLM/KJV+KToMaR1zNXAFwFzydKAhySF9uL8F+QZTj06u/ae+annC4tgSiu02RQaym5r5YKLPaY/oCGswDkB6c9fMuUkQN7e774vVhlSZcT9Vn2opzKIDALbTkyI8YOtvlcLh97/DfUUsOsDCv+biZGs8/Tk6JH5G8tn/gkFjS5VZh5qA6XFARodQbm7xv4/eY97s8OcdYkOfJwVjY7cE/sHiiA4pNUwg+ArH3mCwmRaTOdyaXaYs/bDIP+1SgQJQuo1c7q3k9wir78vjR0MKeb395eiLeCOnVu6l6vZ8dyDgVree9WOsBOd9cjARux5oRzAvue0/13CybtuPR+Jai5vcnL+SBLHQVdCqqrxxUE+VwBzC0Y1lOb3BLUTUDXcLSAbXymwlp8/IyS2F69PFbIVhdY9/YMBsCJZRt0FZyRzkA4xiEpKejs9QfTDnJl60VYGX38bKW+yVAJTkUFVCQciK7NjDKiwrCyWSzf2cJzGVkqxXWgfBoK/Ryn3iK5IX5E+loq/OCuCxbxDyA7PaGqcrN
  template:
    metadata:
      name: mysql-init-scripts
      namespace: mysql-dev
