---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mysql-init-scripts
  namespace: mysql-dev
spec:
  encryptedData:
    init.sql: AgA71sfGl8j56taBi0mkxlurDRLH0kNdB37lM9SkSw4AwJrzzy7xIdxDQIcZ9GNvDX9MY3rFennLg5wJ3BvZAU61ufv6JCOVF1j1bVom+MH1J1yneVkHwou81PlZKXRq5IEy1vppbJhM2dgsundBmvyGqUYGH9OjRuffbASWieT9YO+cAoNJW43axID6Tbq0MxYkdsO0Hzq9Wk1ZzsGhXT+y1ZA3WiGv0vSN0h7sYTzhfgeSDkUdkA5IQ7XHkUHgCsWtnZ/I1avhLfMfoOi+GCK6m19H6iPWXEHXiKN2bOv0pCad8vvNuVlYLvvmE9RSWcbEgQeOiP16EyTyyuMHS+zEf9oBalzGJ2tosS3fkOiK9BEcSys0/9v3wtCY7t2Flk+kXsjL95oBvjKaUWG2QhmY4VVZGFsjonxbaN4c+VtINSAYRzonaQX5Ve0l04YjMQgZueo8UjXw98Cd5wIKijLqpvg993FiJMUrbY7F4nPMgYaO6kTxtpMz5S9qYPQrBOesKxK5jGI3szSytI1GEjByB3unWK0Nir5tn4XqjOtpkMl8rjNKBO5gp+Y3Za5WawckSL/F16Jb1bQ+uRZPa8XJYIITprAtwQCJnCVl36o6hkYq0EopNApk4LthLj+c+KU3G+XSWrOSiGjkv57UtlRtDa2iUAdYAYL0adNAy3F6cI/yuo7MDg77cbO05RzSvfo8znAcV78szPL19Shtm8VWk6wsv9fvSnlddOU/PyDtP8gGIhzj6laa7q8ts1wbuPNiZH30So/wNGshJD7PepOPVuWz/nNuxkNtNgUJTyq79RKJQN3ehiRA2LXoJRmGm02ce5pbFTg6PJ9XtyM2LXVCxAA0DK+Fwh8vNAD88D/UzlJ+0YWvknAJgsVDemEJ2HpcVEepixUjNC4iwaT0AmlNgrKZ/ygWWSRC41MhRORz9B/rudyr
  template:
    metadata:
      name: mysql-init-scripts
      namespace: mysql-dev
