---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mysql-init-scripts
  namespace: mysql-dev
spec:
  encryptedData:
    init.sql: AgCMtrs+yFFteyAAJQRbzpaArtzW8PaYetoREqiIFeo53ulLqfrgESchgUCaDAS/gHyaySwiuE9SdgUKKqgIDdk45ax7hIjrZY9MpmVDfcIV733NooLOltUvYfSqNf/SHfbVtoczj5Lywp5XUvHAaNQeIyONTF27ViRdWh/wx4gt6WQApCiC/IN+IqpDiFCN5hxyViATNi/4JjMNEof9z/OWdpPYd52EEpUBsZIUqZU6hDfF891m/i1vvTT3uvaq9+EA3/fbckLcaCpFptBIXrPlofckS4UkoiKGhYV4Lk03GnP2Z9pM7K3sGa/N97N0Gfesaftv/jva0uc+awnT5OG3D32uSMQgYfB0zX+FHBT395DyRXPBJq17m+LkszPrCNHTepE4OVZF8BMQbFbrr+VEmx7AUn3uDrBV71Svg9A9WsSwyScD/t4PgMKrvBuY80k6xpKvgJjK9IfQQiMInWJRTOVgL4zvHNHHR6qjDlDlqRY0gQ1zONQ6Y6nmV+AkeuJHOGjR3q5U62UFbcddLcmQQ4oDDFn4A/GrP3T6k3CBcxbNMp9JyBdZUMNQPPZAySx1dZXFpgdf86q0vf5hyNTUzxaRAV6zOlNOsYudgH+k9qZHI3rJcZ38DROEtJqD4gVZFH/FMz9O2dkWUAwgoj2vEiyQGR7G7T0eH05kWEW6rWd64LWFLcwyak2ZcVPvLwz4jsMZfItyIVEuFfNpeA8SraBvIkcVNQMNTuLjmo+rvWdrLGJmyXwO0YK0gEiNi5Wo/QXLqflhVbBYLDH4HlyB1yAjO5ZNRZQrxIMHmbs1h2XfD5g4IHwQ+xAPGFbzvjNzhqYREUwYD5xAjvzHjXmadyG3A03QYFjpMYEyCz64MrDZTPWN2S7kzTsIAZJDSxvn8HoczACEnqxuG7wmvhc7342QHPtAYeHx+W7ZtssTvFB80aLJ
  template:
    metadata:
      name: mysql-init-scripts
      namespace: mysql-dev
