---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mysql-init-scripts
  namespace: mysql-dev
spec:
  encryptedData:
    init.sql: AgB//Kadj5C34ndN2V364GyuZmx4JPnzQqn/5/w4akrrx0LhPxSFjGdgMMSpHLjWglTBDGcultRPn6KpTFlYZaaOIzt+hFWKWjSk40Qkl8//qn1ef+kwBvMBupvKIu5f4Xn3cvEqMsGxqIvpf1+9V9SKX2i1rWSJxXBZjZJIvsgGoMdL8o9/Je6Xy/RKnmB9OPWBQzbTTAfA7HCedwNSTp3n6QZglePFOZOlSFX2Q0f+J12Tj1s2sTIEsWW/s7SF90Wv/DklP0JRXmQlW0j6Cwwqro7N3wBRGyFkAY2laabi/AbaIW/PvYAF34/0xaU7CyUabwSxiXh+GsoY1tF2hzKAluBPCDjFhp4LCoDpCabQYqG0Oje1qVKrKsatXUeIP9AVHUPaAZZdhhiRHZqOYO+bYGJU30QamJOaz9QZSCeAHOOM41QhEkK8KCBhDx2gPPUKWeSUBkGiDfsUjRKUdnv1jDfbogidtbmhxQxtRRmFglG9cNqh7vRhq6Uusb6fSXDC975U7wjWHkVoVUuZq8i9OQwebxXADQz3OwtY7CESkWFfhAmHH+Gr/EggbGaf/RSqa90ggB48J3Uqg78Rn/N2S+738uHmpOGrjg26/1xvzMwhkaKTHyPKTdHiewhWlyrL12STO+GNOtatCHpPG0DHGYKUwxuDawPkMbdExpGHT5jC1Aob25cr8nXQVUGmlx1evE/ff5Bxc1t69llE0JogJNfnRWR6iVJ8yZRUdjXKBkN6n74LKfN3Kl9gvYhzBkg3aW5UzNzvy843uN1IhHwoYi0azrPWZXu54hyuCS+ocSeZbyEr7SIgkBanNYJoAwlRJ5cGoTgZ8/mPsMsmF5QtGOoeNAoL116mafkNirFHQ37Xe96N2tvdw6o3XpK5gGogAAWMjm2sQLmucnQI1CfHIpQ/uaiPvt0eANXofE9cyEVDgu/m
  template:
    metadata:
      name: mysql-init-scripts
      namespace: mysql-dev
